apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: headlamp
type: Opaque
stringData:
  client-id: "Ov23liJ8swCvQB96E9bC"
  client-secret: "1d936b39b25cc653cf3bec78820584a0025349f8"
  cookie-secret: "base64:bmEcDENeBRr0f5jnVc/z9TLkgYe19h8WdLMNeQ+mgIY="
